// Lista fontów dla Wolfie Font Swapper.
// SYSTEM_FONTS  – fonty zwykle dostępne lokalnie (nie wymagają pobrania).
// GOOGLE_FONTS  – nazwy rodzin z Google Fonts (ładowane dynamicznie z fonts.googleapis.com).

const SYSTEM_FONTS = [
  "Arial",
  "Arial Black",
  "Arial Narrow",
  "Bahnschrift",
  "Calibri",
  "Cambria",
  "Candara",
  "Comic Sans MS",
  "Consolas",
  "Constantia",
  "Corbel",
  "Courier New",
  "Ebrima",
  "Franklin Gothic Medium",
  "Gabriola",
  "Gadugi",
  "Georgia",
  "Impact",
  "Ink Free",
  "Javanese Text",
  "Leelawadee UI",
  "Lucida Console",
  "Lucida Sans Unicode",
  "Malgun Gothic",
  "Marlett",
  "Microsoft Himalaya",
  "Microsoft JhengHei",
  "Microsoft New Tai Lue",
  "Microsoft PhagsPa",
  "Microsoft Sans Serif",
  "Microsoft Tai Le",
  "Microsoft YaHei",
  "MingLiU-ExtB",
  "Mongolian Baiti",
  "MS Gothic",
  "MV Boli",
  "Myanmar Text",
  "Nirmala UI",
  "Palatino Linotype",
  "Segoe Print",
  "Segoe Script",
  "Segoe UI",
  "Segoe UI Emoji",
  "Segoe UI Historic",
  "Segoe UI Symbol",
  "SimSun",
  "Sitka",
  "Sylfaen",
  "Symbol",
  "Tahoma",
  "Times New Roman",
  "Trebuchet MS",
  "Verdana",
  "Webdings",
  "Wingdings",
  "Yu Gothic",
  // Generyczne rodziny CSS:
  "serif",
  "sans-serif",
  "monospace",
  "cursive",
  "fantasy",
  "system-ui"
];

const GOOGLE_FONTS = [
  "ABeeZee","Abel","Abril Fatface","Aclonica","Acme","Alata","Alegreya","Alegreya Sans",
  "Alfa Slab One","Alice","Allura","Almarai","Amaranth","Amatic SC","Anonymous Pro","Anton",
  "Antic Slab","Archivo","Archivo Black","Archivo Narrow","Arimo","Armata","Arsenal","Arvo",
  "Asap","Asap Condensed","Assistant","Asul","Athiti","Atkinson Hyperlegible","Average",
  "Bad Script","Bai Jamjuree","Balsamiq Sans","Bangers","Barlow","Barlow Condensed",
  "Barlow Semi Condensed","Be Vietnam Pro","Bebas Neue","Bellefair","BenchNine","Bitter",
  "Black Ops One","Bodoni Moda","Bree Serif","Bungee","Cabin","Cabin Condensed","Cairo",
  "Caveat","Cardo","Catamaran","Changa","Chakra Petch","Charm","Chivo","Cinzel","Comfortaa",
  "Commissioner","Concert One","Cookie","Cormorant","Cormorant Garamond","Courgette",
  "Crete Round","Crimson Pro","Crimson Text","Cuprum","Dancing Script","DM Mono","DM Sans",
  "DM Serif Display","DM Serif Text","Domine","Dosis","EB Garamond","Eczar","El Messiri",
  "Electrolize","Encode Sans","Exo","Exo 2","Fahkwang","Faustina","Figtree","Fira Code",
  "Fira Sans","Fira Sans Condensed","Fjalla One","Frank Ruhl Libre","Fraunces","Gelasio",
  "Gentium Book Basic","Geologica","Gloria Hallelujah","Gothic A1","Great Vibes","Gruppo",
  "Hammersmith One","Heebo","Hind","Hind Madurai","Hind Siliguri","Holtwood One SC","Hubballi",
  "IBM Plex Mono","IBM Plex Sans","IBM Plex Serif","Inconsolata","Indie Flower","Inknut Antiqua",
  "Inria Sans","Inter","Inter Tight","Itim","Jacques Francois","Jaldi","JetBrains Mono",
  "Josefin Sans","Josefin Slab","Jost","Judson","Julius Sans One","Just Another Hand","Kalam",
  "Kanit","Karla","Katibeh","Kaushan Script","Khand","Kreon","Kufam","Kumbh Sans","Lato",
  "League Gothic","League Spartan","Lexend","Lexend Deca","Libre Barcode 39","Libre Baskerville",
  "Libre Caslon Text","Libre Franklin","Lilita One","Lobster","Lobster Two","Lora",
  "Luckiest Guy","Macondo","Manrope","Marcellus","Markazi Text","Martel","Maven Pro","Merienda",
  "Merriweather","Merriweather Sans","Michroma","Mitr","Monda","Montserrat","Montserrat Alternates",
  "Mukta","Mulish","Nanum Gothic","Nanum Myeongjo","Newsreader","Niconne","Nobile","Notable",
  "Noticia Text","Noto Color Emoji","Noto Sans","Noto Sans JP","Noto Sans KR","Noto Sans SC",
  "Noto Sans TC","Noto Serif","Noto Serif JP","Nunito","Nunito Sans","Old Standard TT","Oleo Script",
  "Onest","Open Sans","Oranienbaum","Orbitron","Oswald","Outfit","Overpass","Overpass Mono",
  "Oxanium","Oxygen","Pacifico","Padauk","Palanquin","Pangolin","Paytone One","Permanent Marker",
  "Petit Formal Script","Philosopher","Phudu","Piazzolla","Play","Playfair Display","Plus Jakarta Sans",
  "Poiret One","Poller One","Poppins","Prata","Prompt","Prosto One","PT Mono","PT Sans",
  "PT Sans Caption","PT Sans Narrow","PT Serif","Public Sans","Quattrocento","Quattrocento Sans",
  "Questrial","Quicksand","Qwigley","Rajdhani","Raleway","Rampart One","Readex Pro","Recursive",
  "Red Hat Display","Red Hat Mono","Red Hat Text","Righteous","Roboto","Roboto Condensed",
  "Roboto Flex","Roboto Mono","Roboto Serif","Roboto Slab","Rokkitt","Ropa Sans","Rowdies",
  "Rozha One","Rubik","Rubik Mono One","Ruda","Sacramento","Sahitya","Sail","Sansita","Sarabun",
  "Sarala","Satisfy","Sawarabi Gothic","Sawarabi Mincho","Scada","Schibsted Grotesk","Secular One",
  "Sen","Shadows Into Light","Share Tech","Share Tech Mono","Shrikhand","Signika","Signika Negative",
  "Silkscreen","Sintony","Six Caps","Slabo 27px","Sofia","Sora","Source Code Pro","Source Sans 3",
  "Source Serif 4","Space Grotesk","Space Mono","Special Elite","Spectral","Staatliches","Stardos Stencil",
  "Syne","Tajawal","Teko","Tenor Sans","Tinos","Titan One","Titillium Web","Tomorrow","Trirong",
  "Trocchi","Trykker","Ubuntu","Ubuntu Condensed","Ubuntu Mono","Unbounded","Unica One","Urbanist",
  "Varela Round","Varta","Vidaloka","Volkhov","Vollkorn","Wallpoet","Work Sans","Yanone Kaffeesatz",
  "Yantramanav","Yellowtail","Yeseva One","Zeyada","Zilla Slab"
];

// Eksport do globalnego zasięgu (popup.js korzysta z tych zmiennych).
window.WOLFIE_FONTS = { SYSTEM_FONTS, GOOGLE_FONTS };
